### ISSUE TITLE
1 Click Setup Fails

### ISSUE THREAD

**Issue by drewdouglass1** [IBM/cp4i-deployment-samples#155]
Created a new 4.5 ROKS cluster and the the CP4I and demos failed to install because of a download error. Full log is below:

The error received is ERROR: Failed to download master.zip from https://github.com/IBM/cp4i-deployment-samples/archive

 2020/12/10 16:06:58 -----  New Workspace Action  -----
 2020/12/10 16:06:58 Request: activitId=ec15c7fe1faeaa515e26bba9590e0741, account=f477a2b0b0fe55f4095c29bcd7852376, owner=drewd@us.ibm.com, requestID=4c23a5dc-e3f3-4294-8d78-f3852d2d0e20
 2020/12/10 16:06:58 Related Activity: action=CLOUDPAK_WORKSPACE_CREATE, workspaceID=cp4i-card-ddd-41d3e450-5747-4b, processedBy=orchestrator-ff8bd9dc7-6slzk
 2020/12/10 16:06:58 Related Workspace: name=cp4i-card-ddd, sourcerelease=(not specified), sourceurl=https://github.com/IBM/cloud-pak/blob/master/repo/case/ibm-cp-integration-2.0.15.tgz
 2020/12/10 16:07:01  --- Ready to execute the CloudpakTemplateCmd command --- 
 2020/12/10 16:07:06 -----  New Action  -----
 2020/12/10 16:07:06 Request: RepoURL=https://github.com/IBM/cloud-pak/blob/master/repo/case/ibm-cp-integration-2.0.15.tgz, WorkspaceSource=Schematics, Branch=, Release=, Folder=
 2020/12/10 16:07:06 Related Activity: action=Cloudpak_CREATE_WORKSPACE,processedBy=sandbox-86fd8d5fd-8v627_3216
 2020/12/10 16:07:06 Getting tar download command
 2020/12/10 16:07:09 No README file is found for the template
 2020/12/10 16:07:09 Done with the Activity
 2020/12/10 16:07:09  --- Ready to execute GeneratePlan command --- 
 2020/12/10 16:07:14  --- Ready to execute GeneratePlan command --- 
 2020/12/10 16:07:14 workspace.template.EnvFile: ee286118-8ae4-4174-b649-7e1e4282878b
 2020/12/10 16:07:14 -----  New Action  -----
 2020/12/10 16:07:14 Request: requestID=4c23a5dc-e3f3-4294-8d78-f3852d2d0e20
 2020/12/10 16:07:15 Related Activity: action=Apply, workspaceID=cp4i-card-ddd-41d3e450-5747-4b, processedByOrchestrator=ID:"4c23a5dc-e3f3-4294-8d78-f3852d2d0e20_ec15c7fe1faeaa515e26bba9590e0741" , processedByJob=cloudpak-job12-ddbcb955c-jhnw4
 
 2020/12/10 16:07:20 -----  Terraform INIT  -----
 2020/12/10 16:07:20 Starting command: terraform init -input=false -no-color
 2020/12/10 16:07:20 Terraform init | 
 2020/12/10 16:07:20 Terraform init | Initializing the backend...
 2020/12/10 16:07:20 Terraform init | 
 2020/12/10 16:07:20 Terraform init | Initializing provider plugins...
 2020/12/10 16:07:20 Terraform init | 
 2020/12/10 16:07:20 Terraform init | The following providers do not have any version constraints in configuration,
 2020/12/10 16:07:20 Terraform init | so the latest version was installed.
 2020/12/10 16:07:20 Terraform init | 
 2020/12/10 16:07:20 Terraform init | To prevent automatic upgrades to new major versions that may contain breaking
 2020/12/10 16:07:20 Terraform init | changes, it is recommended to add version = "..." constraints to the
 2020/12/10 16:07:20 Terraform init | corresponding provider blocks in configuration, with the constraint strings
 2020/12/10 16:07:20 Terraform init | suggested below.
 2020/12/10 16:07:20 Terraform init | 
 2020/12/10 16:07:20 Terraform init | * provider.ibm: version = "~> 1.16"
 2020/12/10 16:07:20 Terraform init | * provider.null: version = "~> 3.0"
 2020/12/10 16:07:20 Terraform init | 
 2020/12/10 16:07:20 Terraform init | Terraform has been successfully initialized!
 2020/12/10 16:07:20 Command finished successfully.
 
 2020/12/10 16:07:20 -----  Terraform SHOW  -----
 2020/12/10 16:07:20 Starting command: terraform show -no-color
 2020/12/10 16:07:23 Terraform show | No state.
 2020/12/10 16:07:23 Command finished successfully.
 
 2020/12/10 16:07:23 -----  Terraform APPLY  -----
 2020/12/10 16:07:23 Starting command: terraform apply -state=terraform.tfstate -auto-approve -no-color -parallelism=1
 2020/12/10 16:07:30 Terraform apply | data.ibm_container_cluster_config.clusterConfig: Refreshing state...
 2020/12/10 16:07:45 Terraform apply | null_resource.uninstall_script: Creating...
 2020/12/10 16:07:45 Terraform apply | null_resource.uninstall_script: Creation complete after 0s [id=4570420991580513806]
 2020/12/10 16:07:45 Terraform apply | null_resource.script: Creating...
 2020/12/10 16:07:45 Terraform apply | null_resource.script: Provisioning with 'local-exec'...
 2020/12/10 16:07:45 Terraform apply | null_resource.script (local-exec): Executing: ["/bin/sh" "-c" "chmod +x ./ibm-cp-integration/inventory/ibmcloudEnablement/files/install/install.sh && ./ibm-cp-integration/inventory/ibmcloudEnablement/files/install/install.sh"]
 2020/12/10 16:07:45 Terraform apply | null_resource.script (local-exec): ℹ INFO: The installation will take approximately 30 minutes to 1.5 hour to complete.
 2020/12/10 16:07:45 Terraform apply | 
 2020/12/10 16:07:45 Terraform apply | 
 2020/12/10 16:07:45 Terraform apply | null_resource.script (local-exec): ℹ INFO: Cleaning up pem file contents
 2020/12/10 16:07:45 Terraform apply | 
 2020/12/10 16:07:45 Terraform apply | null_resource.script (local-exec): -------------------------------------------------------------------------------------------------------------------
 2020/12/10 16:07:45 Terraform apply | 
 2020/12/10 16:07:46 Terraform apply | null_resource.script (local-exec): ❌ ERROR: Failed to download master.zip from https://github.com/IBM/cp4i-deployment-samples/archive
 2020/12/10 16:07:46 Terraform apply | 
 2020/12/10 16:07:46 Terraform apply | null_resource.script (local-exec): -------------------------------------------------------------------------------------------------------------------
 2020/12/10 16:07:46 Terraform apply | 
 2020/12/10 16:07:46 Terraform apply | 
 2020/12/10 16:07:46 Terraform apply | 
 2020/12/10 16:07:46 Terraform apply | 
 2020/12/10 16:07:46 Terraform apply | Warning: External references from destroy provisioners are deprecated
 2020/12/10 16:07:46 Terraform apply | 
 2020/12/10 16:07:46 Terraform apply |   on main.tf line 58, in resource "null_resource" "uninstall_script":
 2020/12/10 16:07:46 Terraform apply |   58: 							environment = {
 2020/12/10 16:07:46 Terraform apply |   59: 								KUBECONFIG = "${data.ibm_container_cluster_config.clusterConfig.config_file_path}"
 2020/12/10 16:07:46 Terraform apply |   60: 							}
 2020/12/10 16:07:46 Terraform apply | 
 2020/12/10 16:07:46 Terraform apply | Destroy-time provisioners and their connection configurations may only
 2020/12/10 16:07:46 Terraform apply | reference attributes of the related resource, via 'self', 'count.index', or
 2020/12/10 16:07:46 Terraform apply | 'each.key'.
 2020/12/10 16:07:46 Terraform apply | 
 2020/12/10 16:07:46 Terraform apply | References to other resources during the destroy phase can cause dependency
 2020/12/10 16:07:46 Terraform apply | cycles and interact poorly with create_before_destroy.
 2020/12/10 16:07:46 Terraform apply | 
 2020/12/10 16:07:46 Terraform apply | Error: Error running command 'chmod +x ./ibm-cp-integration/inventory/ibmcloudEnablement/files/install/install.sh && ./ibm-cp-integration/inventory/ibmcloudEnablement/files/install/install.sh': exit status 1. Output: ℹ INFO: The installation will take approximately 30 minutes to 1.5 hour to complete.
 2020/12/10 16:07:46 Terraform apply | 
 2020/12/10 16:07:46 Terraform apply | 
 2020/12/10 16:07:46 Terraform apply | ℹ INFO: Cleaning up pem file contents
 2020/12/10 16:07:46 Terraform apply | 
 2020/12/10 16:07:46 Terraform apply | -------------------------------------------------------------------------------------------------------------------
 2020/12/10 16:07:46 Terraform apply | 
 2020/12/10 16:07:46 Terraform apply | ❌ ERROR: Failed to download master.zip from https://github.com/IBM/cp4i-deployment-samples/archive
 2020/12/10 16:07:46 Terraform apply | 
 2020/12/10 16:07:46 Terraform apply | -------------------------------------------------------------------------------------------------------------------
 2020/12/10 16:07:46 Terraform apply | 
 2020/12/10 16:07:46 Terraform apply | 
 2020/12/10 16:07:46 Terraform apply | 
 2020/12/10 16:07:46 Terraform apply | 
 2020/12/10 16:07:46 Terraform APPLY error: Terraform APPLY errorexit status 1
 2020/12/10 16:07:46 Could not execute action

**Comment by James-Kirk** [comment]
Hey @drewdouglass1, opened this for you at: https://github.ibm.com/cp4i/icip-issues/issues/2053
